SELECT * FROM SYSCS_DIAG.LOCK_TABLE; /* CHECK TABLE LOCKS */

SELECT * FROM ASSIGN2.AGE_RATING;

SELECT * FROM ASSIGN2.MOVIE;

SELECT * FROM ASSIGN2.MOVIE_CHARACTER_TYPE;

SELECT * FROM ASSIGN2.MOVIE_CHARACTER;

SELECT * FROM ASSIGN2.MOVIE_CINEMA;

SELECT * FROM ASSIGN2.CINEMA_AMENITIES;

SELECT * FROM ASSIGN2.CINEMA;

SELECT * FROM ASSIGN2.ADDRESS;

SELECT * FROM ASSIGN2.CINEMA_HAS_CINEMA_AMENITIES;

SELECT * FROM ASSIGN2.MOVIE_CHARACTER_TYPE WHERE CHARACTER_TYPE='Director';

SELECT * FROM ASSIGN2.MOVIE_HAS_MOVIE_CHARACTER;

SELECT * FROM ASSIGN2.MOVIE WHERE LOWER(TITLE) LIKE LOWER('%the%');

UPDATE ASSIGN2.MOVIE SET RELEASE_DATE = '2014-04-13' WHERE id = 2;
UPDATE ASSIGN2.MOVIE SET RELEASE_DATE = '2014-04-13' WHERE id = 3;
UPDATE ASSIGN2.MOVIE SET RELEASE_DATE = '2014-04-13' WHERE id = 4;

SELECT * FROM ASSIGN2.MOVIE_CINEMA_HAS_TIMES;

SELECT * FROM ASSIGN2.TIMES;

SELECT m.title, m.release_date, c.name, t.day, t.Time FROM ASSIGN2.MOVIE m, ASSIGN2.CINEMA c, ASSIGN2.MOVIE_CINEMA mc, ASSIGN2.MOVIE_CINEMA_HAS_TIMES mct, ASSIGN2.TIMES t
WHERE m.id = 2
AND m.id=mc.movie_id
AND c.id=mc.cinema_id
AND mc.id=mct.movie_cinema_id
AND mct.times_id=t.id;

DELETE FROM ASSIGN2.TIMES WHERE id=7;

DELETE FROM ASSIGN2.MOVIE_CINEMA_HAS_TIMES WHERE times_id=7;

ALTER TABLE ASSIGN2.TIMES
ADD CONSTRAINT times_unique UNIQUE (Day, Time);

SELECT * FROM ASSIGN2.MOVIE_CINEMA WHERE MOVIE_ID=2;

SELECT * FROM ASSIGN2.MOVIE_CINEMA_HAS_TIMES WHERE MOVIE_CINEMA_ID IN (1,3,8);

SELECT * FROM ASSIGN2.CINEMA WHERE ID IN (1,2,15);

SELECT * FROM ASSIGN2.USER_TYPE;

SELECT * FROM ASSIGN2.CINEMA_USER;
